// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QuanLyKhachHang.Models;

#nullable disable

namespace QuanLyKhachHang.Migrations
{
    [DbContext(typeof(QuanLyCuaHangDbContext))]
    partial class QuanLyCuaHangDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("QuanLyKhachHang.Models.ChiTieu", b =>
                {
                    b.Property<int>("MaChiTieu")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaChiTieu"));

                    b.Property<DateOnly?>("NgayChi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("date")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("NoiDungChi")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<decimal>("SoTien")
                        .HasColumnType("decimal(18, 2)");

                    b.HasKey("MaChiTieu")
                        .HasName("PK__ChiTieu__CDF0A11778D2EEAF");

                    b.ToTable("ChiTieu", (string)null);
                });

            modelBuilder.Entity("QuanLyKhachHang.Models.DichVu", b =>
                {
                    b.Property<int>("MaDichVu")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaDichVu"));

                    b.Property<string>("GhiChuDichVu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("GiaBuoiLe")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18, 2)")
                        .HasDefaultValue(0m);

                    b.Property<decimal?>("GiaTronGoi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18, 2)")
                        .HasDefaultValue(0m);

                    b.Property<bool?>("LieuTrinh")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<int?>("SoBuoiMacDinh")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.Property<string>("TenDichVu")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("MaDichVu")
                        .HasName("PK__DichVu__C0E6DE8F71B5D87C");

                    b.ToTable("DichVu", (string)null);
                });

            modelBuilder.Entity("QuanLyKhachHang.Models.GiaoDich", b =>
                {
                    b.Property<int>("MaGiaoDich")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaGiaoDich"));

                    b.Property<string>("GhiChu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HinhThucThanhToan")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool?>("IsConsultedByPA")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("LoaiHinh")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("MaDichVu")
                        .HasColumnType("int");

                    b.Property<int?>("MaKhachHang")
                        .HasColumnType("int");

                    b.Property<int?>("MaNhanVienSale")
                        .HasColumnType("int");

                    b.Property<int?>("MaNhanVienThucHien")
                        .HasColumnType("int");

                    b.Property<int?>("MaSanPham")
                        .HasColumnType("int");

                    b.Property<DateTime?>("NgayGiaoDich")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<decimal?>("SoTienNo")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("decimal(19, 2)")
                        .HasComputedColumnSql("([TongTien]-[ThucThu])", false);

                    b.Property<string>("TenKhachHang")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TenMatHang")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("TenNhanVienSale")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TenNhanVienThucHien")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal?>("ThucThu")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18, 2)")
                        .HasDefaultValue(0m);

                    b.Property<decimal?>("TongTien")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18, 2)")
                        .HasDefaultValue(0m);

                    b.HasKey("MaGiaoDich")
                        .HasName("PK__GiaoDich__0A2A24EBE9429492");

                    b.HasIndex("MaDichVu");

                    b.HasIndex("MaKhachHang");

                    b.HasIndex("MaNhanVienSale");

                    b.HasIndex("MaNhanVienThucHien");

                    b.HasIndex("MaSanPham");

                    b.ToTable("GiaoDich", null, t =>
                        {
                            t.HasTrigger("trg_CapNhatTienDoTuDong");
                        });

                    b.HasAnnotation("SqlServer:UseSqlOutputClause", false);
                });

            modelBuilder.Entity("QuanLyKhachHang.Models.NguoiDung", b =>
                {
                    b.Property<int>("MaNguoiDung")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaNguoiDung"));

                    b.Property<string>("DiaChi")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("MatKhauHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly?>("NgaySinh")
                        .HasColumnType("date");

                    b.Property<DateTime?>("NgayTao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("SoDienThoai")
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)");

                    b.Property<string>("TenDangNhap")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("TienDoLieuTrinh")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasDefaultValue("Chưa đăng ký");

                    b.Property<string>("VaiTro")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("MaNguoiDung")
                        .HasName("PK__NguoiDun__C539D762D714BC45");

                    b.HasIndex(new[] { "SoDienThoai" }, "UQ__NguoiDun__0389B7BD290B2F90")
                        .IsUnique()
                        .HasFilter("[SoDienThoai] IS NOT NULL");

                    b.HasIndex(new[] { "TenDangNhap" }, "UQ__NguoiDun__55F68FC02E9EE42F")
                        .IsUnique();

                    b.ToTable("NguoiDung", (string)null);
                });

            modelBuilder.Entity("QuanLyKhachHang.Models.NhatKyCongViec", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("GhiChu")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("HinhThucThanhToan")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool?>("IsConsultedByPA")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool?>("LaLieuTrinh")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<int?>("MaDichVu")
                        .HasColumnType("int");

                    b.Property<int?>("MaKhachHang")
                        .HasColumnType("int");

                    b.Property<DateTime?>("NgayThucHien")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("TenDichVu")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TenKhachHang")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TenNhanVienSale")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id")
                        .HasName("PK_NhatKyCongViec");

                    b.HasIndex("MaDichVu");

                    b.HasIndex("MaKhachHang");

                    b.ToTable("NhatKyCongViec", (string)null);
                });

            modelBuilder.Entity("QuanLyKhachHang.Models.SanPham", b =>
                {
                    b.Property<int>("MaSanPham")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaSanPham"));

                    b.Property<decimal?>("DonGia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18, 2)")
                        .HasDefaultValue(0m);

                    b.Property<int?>("SoLuong")
                        .HasColumnType("int");

                    b.Property<string>("TenSanPham")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("MaSanPham")
                        .HasName("PK__SanPham__FAC7442DE7BF3480");

                    b.ToTable("SanPham", (string)null);
                });

            modelBuilder.Entity("QuanLyKhachHang.Models.GiaoDich", b =>
                {
                    b.HasOne("QuanLyKhachHang.Models.DichVu", "MaDichVuNavigation")
                        .WithMany("GiaoDiches")
                        .HasForeignKey("MaDichVu")
                        .HasConstraintName("FK__GiaoDich__MaDich__5AEE82B9");

                    b.HasOne("QuanLyKhachHang.Models.NguoiDung", "MaKhachHangNavigation")
                        .WithMany("GiaoDichMaKhachHangNavigations")
                        .HasForeignKey("MaKhachHang")
                        .HasConstraintName("FK__GiaoDich__MaKhac__59063A47");

                    b.HasOne("QuanLyKhachHang.Models.NguoiDung", "MaNhanVienSaleNavigation")
                        .WithMany("GiaoDichMaNhanVienSaleNavigations")
                        .HasForeignKey("MaNhanVienSale")
                        .HasConstraintName("FK__GiaoDich__MaNhan__5BE2A6F2");

                    b.HasOne("QuanLyKhachHang.Models.NguoiDung", "MaNhanVienThucHienNavigation")
                        .WithMany("GiaoDichMaNhanVienThucHienNavigations")
                        .HasForeignKey("MaNhanVienThucHien")
                        .HasConstraintName("FK__GiaoDich__MaNhan__5CD6CB2B");

                    b.HasOne("QuanLyKhachHang.Models.SanPham", "MaSanPhamNavigation")
                        .WithMany("GiaoDiches")
                        .HasForeignKey("MaSanPham")
                        .HasConstraintName("FK__GiaoDich__MaSanP__59FA5E80");

                    b.Navigation("MaDichVuNavigation");

                    b.Navigation("MaKhachHangNavigation");

                    b.Navigation("MaNhanVienSaleNavigation");

                    b.Navigation("MaNhanVienThucHienNavigation");

                    b.Navigation("MaSanPhamNavigation");
                });

            modelBuilder.Entity("QuanLyKhachHang.Models.NhatKyCongViec", b =>
                {
                    b.HasOne("QuanLyKhachHang.Models.DichVu", "MaDichVuNavigation")
                        .WithMany()
                        .HasForeignKey("MaDichVu")
                        .HasConstraintName("FK_NhatKyCongViec_DichVu");

                    b.HasOne("QuanLyKhachHang.Models.NguoiDung", "MaKhachHangNavigation")
                        .WithMany()
                        .HasForeignKey("MaKhachHang")
                        .HasConstraintName("FK_NhatKyCongViec_KhachHang");

                    b.Navigation("MaDichVuNavigation");

                    b.Navigation("MaKhachHangNavigation");
                });

            modelBuilder.Entity("QuanLyKhachHang.Models.DichVu", b =>
                {
                    b.Navigation("GiaoDiches");
                });

            modelBuilder.Entity("QuanLyKhachHang.Models.NguoiDung", b =>
                {
                    b.Navigation("GiaoDichMaKhachHangNavigations");

                    b.Navigation("GiaoDichMaNhanVienSaleNavigations");

                    b.Navigation("GiaoDichMaNhanVienThucHienNavigations");
                });

            modelBuilder.Entity("QuanLyKhachHang.Models.SanPham", b =>
                {
                    b.Navigation("GiaoDiches");
                });
#pragma warning restore 612, 618
        }
    }
}
